# two dataset

In [7]:
import pandas as pd
l65_df = pd.read_csv("RT65_words.csv", dtype={'strong_num': str})
hb_df = pd.read_csv("biblehub_hb_en_direct.csv", dtype={'strong_num': str})

# check missing 65

## check reverse

In [8]:
void_hb_df = None #already checked @ merge_Heb_lxx_enc_1965
def prepare_grouped(l65_df, hb_df):
    l65_g = l65_df.groupby(["book", "chapter", "verse"])
    hb_g = hb_df.groupby(["book", "chapter", "verse"])
    return l65_g, hb_g
l65_g, hb_g = prepare_grouped(l65_df, hb_df)

## mapping!!

In [9]:
# lv vietturis : ebreju vietturis
l65_to_hb={
('1_chronicles', 5, 27) : ('1_chronicles', 6, 1),
('1_chronicles', 5, 28) : ('1_chronicles', 6, 2),
('1_chronicles', 5, 29) : ('1_chronicles', 6, 3),
('1_chronicles', 5, 30) : ('1_chronicles', 6, 4),
('1_chronicles', 5, 31) : ('1_chronicles', 6, 5),
('1_chronicles', 5, 32) : ('1_chronicles', 6, 6),
('1_chronicles', 5, 33) : ('1_chronicles', 6, 7),
('1_chronicles', 5, 34) : ('1_chronicles', 6, 8),
('1_chronicles', 5, 35) : ('1_chronicles', 6, 9),
('1_chronicles', 5, 36) : ('1_chronicles', 6, 10),
('1_chronicles', 5, 37) : ('1_chronicles', 6, 11),
('1_chronicles', 5, 38) : ('1_chronicles', 6, 12),
('1_chronicles', 5, 39) : ('1_chronicles', 6, 13),
('1_chronicles', 5, 40) : ('1_chronicles', 6, 14),
('1_chronicles', 5, 41) : ('1_chronicles', 6, 15)
}
for i in range(1, 66+1):
    l65_to_hb[('1_chronicles', 6, i)]=('1_chronicles', 6, i+15)

for l, h in zip(range(1, 14+1), range(21, 34+1)):
    l65_to_hb[('1_kings', 5, l)]=('1_kings', 4, h)

for i in range(15, 32+1):
    l65_to_hb[('1_kings', 5, i)]=('1_kings', 5, i-14)



#merge 43 + 44
l65_to_hb_merge = {
    (('1_kings', 22, 43), ('1_kings', 22, 44)): ('1_kings', 22, 43)
}

#now update mapping
for i in range(43, 53+1):
    l65_to_hb[('1_kings', 22, i+1)]=('1_kings', 22, i)
#1 samuel 20:42+
l65_to_hb[('1_samuel', 20, 43)]=('1_samuel', 21, 1)
for i in range(1, 13+1):
    l65_to_hb[('1_samuel', 21, i)]=('1_samuel', 21, i+1)
#14, 15 merged => 14 hebrw
l65_to_hb_merge[(('1_samuel', 21, 14), ('1_samuel', 21, 15))] = ('1_samuel', 21, 15)

#1 samuel 23:28+
l65_to_hb[('1_samuel', 24, 1)] = ('1_samuel', 23, 29)
for i in range(2, 23+1):
    l65_to_hb[('1_samuel', 24, i)]=('1_samuel', 24, i-1)

#2chronicles 2:1
l65_to_hb[('2_chronicles', 1, 18)] = ('2_chronicles', 2, 1)
for i in range(1, 17+1):
    l65_to_hb[('2_chronicles', 2, i)]=('2_chronicles', 2, i+1)

#2chronicles 14:1
l65_to_hb[('2_chronicles', 13, 23)] = ('2_chronicles', 14, 1)
for i in range(1, 14+1):
    l65_to_hb[('2_chronicles', 14, i)]=('2_chronicles', 14, i+1)

#2kings 12:1-21
l65_to_hb[('2_kings', 12, 1)] = ('2_kings', 11, 21)
for i in range(2, 22+1):
    l65_to_hb[('2_kings', 12, i)]=('2_kings', 12, i-1)

In [10]:
#2 sam 18:33
l65_to_hb[('2_samuel', 19, 1)] = ('2_samuel', 18, 33)
for i in range(2, 44+1):
    l65_to_hb[('2_samuel', 19, i)]=('2_samuel', 19, i-1)

#daniel 3
l65_to_hb[('daniel', 3, 31)] = ('daniel', 4, 1)
#obsolote, now merge ir rghtfully updating the map.l65_to_hb[('daniel', 3, 32)] = ('daniel', 4, 2), 3

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1 O T R Ā D I !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 1 lv verse = 2x heb verses, TODO: SPLIT THEM ON WORD BEING LAST IN 1st part
l65_to_hb_merge[(('daniel', 3, 32), "darījis")] = (('daniel', 4, 2), ('daniel', 4, 3))
for i in range(1, 34+1):
    l65_to_hb[('daniel', 4, i)] = ('daniel', 4, i+3)

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1 O T R Ā D I !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 1 lv verse = 2x heb verses, TODO: SPLIT THEM ON WORD BEING LAST IN 1st part
l65_to_hb_merge[(('daniel', 5, 30), "nogalināts")] = (('daniel', 5, 30), ('daniel', 5, 31))

l65_to_hb[('deuteronomy', 13, 1)] = ('deuteronomy', 12, 32)
for i in range(2, 19+1):
    l65_to_hb[('deuteronomy', 13, i)]=('deuteronomy', 13, i-1)

l65_to_hb[('deuteronomy', 23, 1)] = ('deuteronomy', 22, 30)
for i in range(2, 26+1):
    l65_to_hb[('deuteronomy', 23, i)]=('deuteronomy', 23, i-1)

l65_to_hb[('deuteronomy', 28, 69)] = ('deuteronomy', 29, 1)
l65_to_hb_merge[(('deuteronomy', 29, 1), ('deuteronomy', 29, 2))]=('deuteronomy', 29, 2)

#ecclesiates
l65_to_hb[('ecclesiastes', 4, 17)] = ('ecclesiastes', 5, 1)
for i in range(1, 19+1):
    l65_to_hb[('ecclesiastes', 5, i)]=('ecclesiastes', 5, i+1)

l65_to_hb[('exodus', 1, 21)] = ('exodus', 1, 22)

l65_to_hb[('exodus', 7, 26)] = ('exodus', 8, 1)
l65_to_hb[('exodus', 7, 27)] = ('exodus', 8, 2)
l65_to_hb[('exodus', 7, 28)] = ('exodus', 8, 3)
l65_to_hb[('exodus', 7, 29)] = ('exodus', 8, 4)
for i in range(1, 28+1):
    l65_to_hb[('exodus', 8, i)]=('exodus', 8, i+4)

l65_to_hb[('exodus', 21, 37)] = ('exodus', 22, 1)
for i in range(1, 30+1):
    l65_to_hb[('exodus', 22, i)]=('exodus', 22, i+1)

In [11]:
#ezekiel
for i in range(45, 49+1):
    l65_to_hb[('ezekiel', 21, i-44)]=('ezekiel', 20, i)
for i in range(6, 37+1):
    l65_to_hb[('ezekiel', 21, i)]=('ezekiel', 21, i-5)

# genesis 3 panti savienoti vienā un izlaista 1 tauta
l65_to_hb_merge[(('genesis', 15, 19), "kadmoniešus", "refajiešus")] = (('genesis', 15, 19), ('genesis', 15, 20), ('genesis', 15, 21))

l65_to_hb_merge[(('genesis', 24, 65),('genesis', 24, 66))] = ('genesis', 24, 65)
for i in range(67, 68+1):
    l65_to_hb[('genesis', 24, i)]=('genesis', 24, i-1)


l65_to_hb[('genesis', 32, 1)]=('genesis', 31, 55)
for i in range(2, 33+1):
    l65_to_hb[('genesis', 32, i)]=('genesis', 32, i-1)

#hosea 1
l65_to_hb[('hosea', 2, 1)] = ('hosea', 1, 10)
l65_to_hb[('hosea', 2, 2)] = ('hosea', 1, 11)
for i in range(3, 25+1):
    l65_to_hb[('hosea', 2, i)]=('hosea', 2, i-2)

l65_to_hb[('hosea', 12, 1)] = ('hosea', 11, 12)
for i in range(2, 15+1):
    l65_to_hb[('hosea', 12, i)]=('hosea', 12, i-1)

l65_to_hb[('hosea', 14, 1)] =('hosea', 13, 16)
for i in range(2, 10+1):
    l65_to_hb[('hosea', 14, i)]=('hosea', 14, i-1)

#isaiah
l65_to_hb[('isaiah', 8, 23)] = ('isaiah', 9, 1)
for i in range(1, 20+1):
    l65_to_hb[('isaiah', 9, i)]=('isaiah', 9, i+1)

l65_to_hb[('jeremiah', 8, 23)] = ('jeremiah', 9, 1)
for i in range(1, 25+1):
    l65_to_hb[('jeremiah', 9, i)]=('jeremiah', 9, i+1)

# job
for i in range(25, 32+1):
    l65_to_hb[('job', 40, i)]=('job', 41, i-24)
for i in range(1, 26+1):
    l65_to_hb[('job', 41, i)]=('job', 41, i+8)
#joel
for i in range(1, 5+1):
    l65_to_hb[('joel', 3, i)]=('joel', 2, i+27)
for i in range(1, 21+1):
    l65_to_hb[('joel', 4, i)]=('joel', 3, i)

#jonah
l65_to_hb[('jonah', 2, 1)] = ('jonah', 1, 17)
for i in range(2, 11+1):
    l65_to_hb[('jonah', 2, i)]=('jonah', 2, i-1)

#leviticus
for i in range(20, 26+1):
    l65_to_hb[('leviticus', 5, i)]=('leviticus', 6, i-19)
for i in range(1, 23+1):
    l65_to_hb[('leviticus', 6, i)]=('leviticus', 6, i+7)

#malachi
for i in range(19, 24+1):
    l65_to_hb[('malachi', 3, i)]=('malachi', 4, i-18)
#malachi 4 in Latvian does not exist!!

#micah
l65_to_hb[('micah', 4, 14)] = ('micah', 5, 1)
for i in range(1, 14+1):
    l65_to_hb[('micah', 5, i)]=('micah', 5, i+1)

#nahum
l65_to_hb[('nahum', 2, 1)] = ('nahum', 1, 15)
for i in range(2, 14+1):
    l65_to_hb[('nahum', 2, i)]=('nahum', 2, i-1)

#nehemiah
l65_to_hb[('nehemiah', 10, 1)] = ('nehemiah', 9, 38)
for i in range(2, 40+1):
    l65_to_hb[('nehemiah', 10, i)]=('nehemiah', 10, i-1)

In [12]:
#numbers
for i in range(36, 50+1):
    l65_to_hb[('numbers', 17, i-35)]=('numbers', 16, i)
for i in range(16, 28+1):
    l65_to_hb[('numbers', 17, i)]=('numbers', 17, i-15)

l65_to_hb[('numbers', 30, 1)] = ('numbers', 29, 40)
for i in range(2, 17+1):
    l65_to_hb[('numbers', 30, i)]=('numbers', 30, i-1)

#psalms
def add_psalms_merging_verse_1_in_1965(chap, maxverse):
    l65_to_hb_merge[(('psalms', chap, 1),('psalms', chap, 2))] = ('psalms', chap, 1)
    for i in range(3, maxverse+1):
        l65_to_hb[('psalms', chap, i)]=('psalms', chap, i-1)
        
add_psalms_merging_verse_1_in_1965(3, 9)
add_psalms_merging_verse_1_in_1965(4, 9)
add_psalms_merging_verse_1_in_1965(5, 13)
add_psalms_merging_verse_1_in_1965(6, 11)
add_psalms_merging_verse_1_in_1965(7, 18)
add_psalms_merging_verse_1_in_1965(8, 10)
add_psalms_merging_verse_1_in_1965(9, 21)
add_psalms_merging_verse_1_in_1965(11, 8)
add_psalms_merging_verse_1_in_1965(12, 9)
add_psalms_merging_verse_1_in_1965(13, 7)
add_psalms_merging_verse_1_in_1965(18, 51)
add_psalms_merging_verse_1_in_1965(19, 15)
add_psalms_merging_verse_1_in_1965(20, 10)
add_psalms_merging_verse_1_in_1965(21, 14)
add_psalms_merging_verse_1_in_1965(22, 32)
add_psalms_merging_verse_1_in_1965(30, 13)
#so far ok, therefore will leave the rest of psalms as is no check
add_psalms_merging_verse_1_in_1965(31, 25)
add_psalms_merging_verse_1_in_1965(34, 23)
add_psalms_merging_verse_1_in_1965(36, 13)
add_psalms_merging_verse_1_in_1965(38, 23)
add_psalms_merging_verse_1_in_1965(39, 14)
add_psalms_merging_verse_1_in_1965(40, 18)
add_psalms_merging_verse_1_in_1965(41, 14)
add_psalms_merging_verse_1_in_1965(42, 12)
add_psalms_merging_verse_1_in_1965(44, 27)
add_psalms_merging_verse_1_in_1965(45, 18)
add_psalms_merging_verse_1_in_1965(46, 12)
add_psalms_merging_verse_1_in_1965(47, 10)
add_psalms_merging_verse_1_in_1965(48, 15)
add_psalms_merging_verse_1_in_1965(49, 21)
add_psalms_merging_verse_1_in_1965(51, 20)
add_psalms_merging_verse_1_in_1965(51, 21)
add_psalms_merging_verse_1_in_1965(52, 10)
add_psalms_merging_verse_1_in_1965(52, 11)
add_psalms_merging_verse_1_in_1965(53, 7)
add_psalms_merging_verse_1_in_1965(54, 8)
add_psalms_merging_verse_1_in_1965(54, 9)
add_psalms_merging_verse_1_in_1965(55, 24)
add_psalms_merging_verse_1_in_1965(56, 14)
add_psalms_merging_verse_1_in_1965(57, 12)
add_psalms_merging_verse_1_in_1965(58, 12)
add_psalms_merging_verse_1_in_1965(59, 18)
add_psalms_merging_verse_1_in_1965(60, 13)
add_psalms_merging_verse_1_in_1965(60, 14)
add_psalms_merging_verse_1_in_1965(61, 9)
add_psalms_merging_verse_1_in_1965(62, 13)
add_psalms_merging_verse_1_in_1965(63, 12)
add_psalms_merging_verse_1_in_1965(64, 11)
add_psalms_merging_verse_1_in_1965(65, 14)
add_psalms_merging_verse_1_in_1965(67, 8)
add_psalms_merging_verse_1_in_1965(68, 36)
add_psalms_merging_verse_1_in_1965(69, 37)
add_psalms_merging_verse_1_in_1965(70, 6)
add_psalms_merging_verse_1_in_1965(75, 11)
add_psalms_merging_verse_1_in_1965(76, 13)
add_psalms_merging_verse_1_in_1965(77, 21)
add_psalms_merging_verse_1_in_1965(80, 20)
add_psalms_merging_verse_1_in_1965(81, 17)
add_psalms_merging_verse_1_in_1965(83, 19)
add_psalms_merging_verse_1_in_1965(84, 13)
add_psalms_merging_verse_1_in_1965(85, 14)
add_psalms_merging_verse_1_in_1965(88, 19)
add_psalms_merging_verse_1_in_1965(89, 53)
add_psalms_merging_verse_1_in_1965(92, 16)
add_psalms_merging_verse_1_in_1965(102, 29)
add_psalms_merging_verse_1_in_1965(108, 14)
add_psalms_merging_verse_1_in_1965(140, 14)
add_psalms_merging_verse_1_in_1965(142, 8)

#song
l65_to_hb_merge[(('songs', 4, 16),('songs', 4, 17))] = ('songs', 4, 16)
l65_to_hb[('songs', 7, 1)] = ('songs', 6, 13)
for i in range(2, 14+1):
    l65_to_hb[('songs', 7, i)]=('songs', 7, i-1)

#zechariah
for i in range(18, 21+1):
    l65_to_hb[('zechariah', 2, i-17)]=('zechariah', 1, i)
for i in range(5, 17+1):
    l65_to_hb[('zechariah', 2, i)]=('zechariah', 2, i-4)
    
# ebreju vietturis : lv vietturis
hb_to_l65 = {v: k for k, v in l65_to_hb.items() if v[0]!= '!'}
hb_to_l65_merge = {v: k for k, v in l65_to_hb_merge.items()}
for k, v in l65_to_hb_merge.items():
    #multiple hebrews to single latvian
    if isinstance(v[1], tuple):
        for resolvedVerse in v:
            #this is case where split string is specified for single latvian verse
            if(isinstance(k[0], tuple) and isinstance(k[1], str)):
                hb_to_l65[resolvedVerse] = ("!"+k[0][0], k[0][1], k[0][2])
                l65_to_hb[k[0]] = ("!", -1, -1)
            #also never happens in current list, what was the reasoning putting else here, "just so that it is"?
            else:
                hb_to_l65[resolvedVerse] = ("!"+k[0], k[1], k[2])
                l65_to_hb[k[0]] = ("!", -1, -1)
#value is single hebrew verse. so if key 2nd is tuple not string then
    elif isinstance(k[1], tuple):
        #where to split the hebrew verse (no case actually in current list!
        if(isinstance(v[0], tuple) and isinstance(v[1], str)):
            for resolvedVerse in k:
                hb_to_l65[resolvedVerse] = ("!"+v[0][0], v[0][1], v[0][2])
                hb_to_l65[v[0]] = ("!", -2, -2)
        #single heb verse maps to multiple lvs, so put pointer mark ! (watch merges instead of direct)
        #and the rest two just placeholders so that they are not misused anywhere as misguiding references
        else:
            for resolvedVerse in k:
                l65_to_hb[resolvedVerse] = ("!"+v[0], v[1], v[2])
            #print(v[0])
            hb_to_l65[v] = ("!", -2, -2)
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IZLAISTS PANTS 1965
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
hb_to_l65[('exodus', 1, 21)] = None

## lv not in heb index

In [13]:
rkeyss = sorted(l65_g.groups.keys())
for i, key in enumerate(rkeyss):
    b, chapter, verse = key
    if key not in hb_g.groups.keys() and key not in l65_to_hb.keys():
        print(key)

## heb not in lv (direct)

In [14]:
keyss = sorted(hb_g.groups.keys())
for i, key in enumerate(keyss):
    b, chapter, verse = key
    if key not in l65_g.groups.keys()  and key not in hb_to_l65.keys():
        print(key)

In [15]:
l65_g.groups[list(l65_to_hb.keys())[0]]

Index([238730, 238731, 238732, 238733, 238734, 238735, 238736, 238737], dtype='int64')

In [16]:
l65_g.get_group(list(l65_to_hb.keys())[0])

                book  chapter  verse  word_idx      text
238730  1_chronicles        5     27         0        Un
238731  1_chronicles        5     27         1    Levija
238732  1_chronicles        5     27         2      dēli
238733  1_chronicles        5     27         3      bija
238734  1_chronicles        5     27         4   Geršons
238735  1_chronicles        5     27         5    Kehats
238736  1_chronicles        5     27         6        un
238737  1_chronicles        5     27         7  Merārijs

In [17]:
hb_g.get_group(list(l65_to_hb.values())[0])

,verse,word,form,form_en,strong_num,strong_title,strong_en_title,translit,translit_title,book,chapter
298192,1,0,בְּנֵ֖י,The sons of,1121,"1121: 1) son, grandson, child, member of a gro...",N‑mpc,bə·nê,be·Nei: The sons of -- Occurrence 785 of 1283.,1_chronicles,6
298193,1,1,לֵוִ֑י,Levi,3878,3878: Levi = joined to<BR> 1) the 3rd son of J...,N‑proper‑ms,lê·wî;,le·Vi;: Levi -- Occurrence 26 of 42.,1_chronicles,6
298194,1,2,גֵּרְשׁ֕וֹן,[were] Gershon,1648,1648: Gershon or Gershom = exile<BR> 1) firstb...,N‑proper‑ms,gê·rə·šō·wn,ge·re·Shon: [were] Gershon -- Occurrence 14 of...,1_chronicles,6
298195,1,3,קְהָ֖ת,Kohath,6955,6955: Kohath = assembly<BR> 1) the 2nd of the ...,N‑proper‑ms,qə·hāṯ,ke·Hat: Kohath -- Occurrence 16 of 27.,1_chronicles,6
298196,1,4,וּמְרָרִֽי׃,and Merari,4847,4847: Merari = bitter<BR> 1) the 3rd son of Le...,Conj‑w|N‑proper‑ms,ū·mə·rā·rî.,u·me·ra·Ri.: and Merari -- Occurrence 4 of 6.,1_chronicles,6

# 2. / 3 add greek

In [18]:
strongs_df = pd.read_csv("greek-enh-lxx-apo-OT-blb.csv", dtype={'strong_num': str})
strongs_g, hb_g = prepare_grouped(strongs_df, hb_df)

/tmp/ipykernel_2250177/2046713390.py:1: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  strongs_df = pd.read_csv("greek-enh-lxx-apo-OT-blb.csv", dtype={'strong_num': str})

In [19]:
strongs_df[:3]

,form,strong_num,strong_en_title,book,chapter,verse,word,is_patched,form_en,strong_title
0,ἐν,1722,Prep,genesis,1,1,0,NaN,NaN,NaN
1,ἀρχῇ,746,N-DSF,genesis,1,1,1,NaN,NaN,NaN
2,ἐποίησεν,4160,V-AAI-3S,genesis,1,1,2,NaN,NaN,NaN

# 3. / 3 Save .txts

In [20]:
from collections import defaultdict

all_keys = sorted(hb_g.groups.keys())

chapters_map = defaultdict(list)
for b, c, v in all_keys:
    chapters_map[(b, c)].append((b, c, v))
# 2. Iterējam cauri nodaļām

In [21]:
hb_g.groups

{('1_chronicles', 1, 1): [301652, 301653, 301654], ('1_chronicles', 1, 2): [301655, 301656, 301657], ('1_chronicles', 1, 3): [301658, 301659, 301660], ('1_chronicles', 1, 4): [301661, 301662, 301663, 301664, 301665], ('1_chronicles', 1, 5): [301666, 301667, 301668, 301669, 301670, 301671, 301672, 301673, 301674, 301675], ('1_chronicles', 1, 6): [301676, 301677, 301678, 301679, 301680], ('1_chronicles', 1, 7): [301681, 301682, 301683, 301684, 301685, 301686, 301687], ('1_chronicles', 1, 8): [301688, 301689, 301690, 301691, 301692, 301693], ('1_chronicles', 1, 9): [301694, 301695, 301696, 301697, 301698, 301699, 301700, 301701, 301702, 301703, 301704, 301705], ('1_chronicles', 1, 10): [301706, 301707, 301708, 301709, 301710, 301711, 301712, 301713, 301714, 301715], ('1_chronicles', 1, 11): [301716, 301717, 301718, 301719, 301720, 301721, 301722, 301723, 301724, 301725, 301726], ('1_chronicles', 1, 12): [301727, 301728, 301729, 301730, 301731, 301732, 301733, 301734, 301735, 301736, 301737], ('1_chronicles', 1, 13): [301738, 301739, 301740, 301741, 301742, 301743, 301744], ('1_chronicles', 1, 14): [301745, 301746, 301747, 301748, 301749, 301750], ('1_chronicles', 1, 15): [301751, 301752, 301753, 301754, 301755, 301756], ('1_chronicles', 1, 16): [301757, 301758, 301759, 301760, 301761, 301762, 301763], ('1_chronicles', 1, 17): [301764, 301765, 301766, 301767, 301768, 301769, 301770, 301771, 301772, 301773, 301774, 301775], ('1_chronicles', 1, 18): [301776, 301777, 301778, 301779, 301780, 301781, 301782, 301783], ('1_chronicles', 1, 19): [301784, 301785, 301786, 301787, 301788, 301789, 301790, 301791, 301792, 301793, 301794, 301795, 301796, 301797], ('1_chronicles', 1, 20): [301798, 301799, 301800, 301801, 301802, 301803, 301804, 301805, 301806, 301807], ('1_chronicles', 1, 21): [301808, 301809, 301810, 301811, 301812, 301813], ('1_chronicles', 1, 22): [301814, 301815, 301816, 301817, 301818, 301819], ('1_chronicles', 1, 23): [301820, 301821, 301822, 301823, 301824, 301825, 301826, 301827, 301828, 301829, 301830], ('1_chronicles', 1, 24): [301831, 301832, 301833], ('1_chronicles', 1, 25): [301834, 301835, 301836], ('1_chronicles', 1, 26): [301837, 301838, 301839], ('1_chronicles', 1, 27): [301840, 301841, 301842, 301843], ('1_chronicles', 1, 28): [301844, 301845, 301846, 301847, 301848], ('1_chronicles', 1, 29): [301849, 301850, 301851, 301852, 301853, 301854, 301855, 301856], ('1_chronicles', 1, 30): [301857, 301858, 301859, 301860, 301861], ('1_chronicles', 1, 31): [301862, 301863, 301864, 301865, 301866, 301867, 301868, 301869], ('1_chronicles', 1, 32): [301870, 301871, 301872, 301873, 301874, 301875, 301876, 301877, 301878, 301879, 301880, 301881, 301882, 301883, 301884, 301885, 301886], ('1_chronicles', 1, 33): [301887, 301888, 301889, 301890, 301891, 301892, 301893, 301894, 301895, 301896, 301897, 301898], ('1_chronicles', 1, 34): [301899, 301900, 301901, 301902, 301903, 301904, 301905, 301906, 301907, 301908], ('1_chronicles', 1, 35): [301909, 301910, 301911, 301912, 301913, 301914, 301915, 301916], ('1_chronicles', 1, 36): [301917, 301918, 301919, 301920, 301921, 301922, 301923, 301924, 301925, 301926], ('1_chronicles', 1, 37): [301927, 301928, 301929, 301930, 301931, 301932, 301933], ('1_chronicles', 1, 38): [301934, 301935, 301936, 301937, 301938, 301939, 301940, 301941, 301942], ('1_chronicles', 1, 39): [301943, 301944, 301945, 301946, 301947, 301948, 301949, 301950], ('1_chronicles', 1, 40): [301951, 301952, 301953, 301954, 301955, 301956, 301957, 301958, 301959, 301960, 301961, 301962], ('1_chronicles', 1, 41): [301963, 301964, 301965, 301966, 301967, 301968, 301969, 301970, 301971, 301972, 301973], ('1_chronicles', 1, 42): [301974, 301975, 301976, 301977, 301978, 301979, 301980, 301981, 301982, 301983], ('1_chronicles', 1, 43): [301984, 301985, 301986, 301987, 301988, 301989, 301990, 301991, 301992, 301993, 301994, 301995, 301996, 301997, 301998, 301999, 302000], ('1_chronicles', 1, 44): [302001, 302002, 302003, 302004, 302005, 302006, 302007, 302008], ('1_chronicles', 1, 45): [302009, 302010, 302011, 302012, 302013, 302014, 302015], ('1_chronicles', 1, 46): [302016, 302017, 302018, 302019, 302020, 302021, 302022, 302023, 302024, 302025, 302026, 302027, 302028, 302029, 302030, 302031], ('1_chronicles', 1, 47): [302032, 302033, 302034, 302035, 302036, 302037], ('1_chronicles', 1, 48): [302038, 302039, 302040, 302041, 302042, 302043, 302044], ('1_chronicles', 1, 49): [302045, 302046, 302047, 302048, 302049, 302050, 302051, 302052], ('1_chronicles', 1, 50): [302053, 302054, 302055, 302056, 302057, 302058, 302059, 302060, 302061, 302062, 302063, 302064, 302065, 302066, 302067, 302068, 302069], ('1_chronicles', 1, 51): [302070, 302071, 302072, 302073, 302074, 302075, 302076, 302077, 302078, 302079, 302080, 302081, 302082], ('1_chronicles', 1, 52): [302083, 302084, 302085, 302086, 302087, 302088], ('1_chronicles', 1, 53): [302089, 302090, 302091, 302092, 302093, 302094], ('1_chronicles', 1, 54): [302095, 302096, 302097, 302098, 302099, 302100, 302101, 302102], ('1_chronicles', 2, 1): [296261, 296262, 296263, 296264, 296265, 296266, 296267, 296268, 296269], ('1_chronicles', 2, 2): [296270, 296271, 296272, 296273, 296274, 296275, 296276], ('1_chronicles', 2, 3): [296277, 296278, 296279, 296280, 296281, 296282, 296283, 296284, 296285, 296286, 296287, 296288, 296289, 296290, 296291, 296292, 296293, 296294, 296295, 296296], ('1_chronicles', 2, 4): [296297, 296298, 296299, 296300, 296301, 296302, 296303, 296304, 296305, 296306, 296307, 296308, 296309], ('1_chronicles', 2, 5): [296310, 296311, 296312, 296313, 296314], ('1_chronicles', 2, 6): [296315, 296316, 296317, 296318, 296319, 296320, 296321, 296322, 296323, 296324], ('1_chronicles', 2, 7): [296325, 296326, 296327, 296328, 296329, 296330, 296331, 296332, 296333], ('1_chronicles', 2, 8): [296334, 296335, 296336], ('1_chronicles', 2, 9): [296337, 296338, 296339, 296340, 296341, 296342, 296343, 296344, 296345, 296346, 296347], ('1_chronicles', 2, 10): [296348, 296349, 296350, 296351, 296352, 296353, 296354, 296355, 296356, 296357, 296358], ('1_chronicles', 2, 11): [296359, 296360, 296361, 296362, 296363, 296364, 296365, 296366], ('1_chronicles', 2, 12): [296367, 296368, 296369, 296370, 296371, 296372, 296373, 296374], ('1_chronicles', 2, 13): [296375, 296376, 296377, 296378, 296379, 296380, 296381, 296382, 296383, 296384], ('1_chronicles', 2, 14): [296385, 296386, 296387, 296388], ('1_chronicles', 2, 15): [296389, 296390, 296391, 296392], ('1_chronicles', 2, 16): [296393, 296394, 296395, 296396, 296397, 296398, 296399, 296400, 296401, 296402, 296403], ('1_chronicles', 2, 17): [296404, 296405, 296406, 296407, 296408, 296409, 296410, 296411], ('1_chronicles', 2, 18): [296412, 296413, 296414, 296415, 296416, 296417, 296418, 296419, 296420, 296421, 296422, 296423, 296424, 296425], ('1_chronicles', 2, 19): [296426, 296427, 296428, 296429, 296430, 296431, 296432, 296433, 296434, 296435, 296436], ('1_chronicles', 2, 20): [296437, 296438, 296439, 296440, 296441, 296442, 296443, 296444, 296445], ('1_chronicles', 2, 21): [296446, 296447, 296448, 296449, 296450, 296451, 296452, 296453, 296454, 296455, 296456, 296457, 296458, 296459, 296460, 296461, 296462, 296463], ('1_chronicles', 2, 22): [296464, 296465, 296466, 296467, 296468, 296469, 296470, 296471, 296472, 296473, 296474], ('1_chronicles', 2, 23): [296475, 296476, 296477, 296478, 296479, 296480, 296481, 296482, 296483, 296484, 296485, 296486, 296487, 296488, 296489, 296490, 296491, 296492, 296493], ('1_chronicles', 2, 24): [296494, 296495, 296496, 296497, 296498, 296499, 296500, 296501, 296502, 296503, 296504, 296505, 296506, 296507], ('1_chronicles', 2, 25): [296508, 296509, 296510, 296511, 296512, 296513, 296514, 296515, 296516, 296517, 296518], ('1_chronicles', 2, 26): [296519, 296520, 296521, 296522, 296523, 296524, 296525, 296526, 296527, 296528], ('1_chronicles', 2, 27): [296529, 296530, 296531, 296532, 296533, 296534, 296535, 296536], ('1_chronicles', 2, 28): [296537, 296538, 296539, 296540, 296541, 296542, 296543, 296544, 296545], ('1_chronicles', 2, 29): [296546, 296547, 296548, 296549, 296550, 296551, 296552, 296553, 296554, 296555], ('1_chronicles', 2, 30): [296556, 296557, 296558, 296559, 296560, 296561, 296562, 296563, 296564], ('1_chronicles', 2, 31): [296565, 296566, 296567, 296568, 296569, 296570, 296571, 296572, 296573], ('1_chronicles', 2, 32): [296574, 296575, 296576, 296577, 296578, 296579, 296580, 296581, 296582, 296583, 296584], ('1_chronicles', 2, 33): [296585, 296586, 296587, 296588, 296589, 296590, 296591, 296592], ('1_chronicles', 2, 34): [296593, 296594, 296595, 296596, 296597, 296598, 296599, 296600, 296601, 296602, 296603, 296604], ('1_chronicles', 2, 35): [296605, 296606, 296607, 296608, 296609, 296610, 296611, 296612, 296613, 296614, 296615], ('1_chronicles', 2, 36): [296616, 296617, 296618, 296619, 296620, 296621, 296622, 296623], ('1_chronicles', 2, 37): [296624, 296625, 296626, 296627, 296628, 296629, 296630, 296631], ('1_chronicles', 2, 38): [296632, 296633, 296634, 296635, 296636, 296637, 296638, 296639], ('1_chronicles', 2, 39): [296640, 296641, 296642, 296643, 296644, 296645, 296646, 296647], ('1_chronicles', 2, 40): [296648, 296649, 296650, 296651, 296652, 296653, 296654, 296655], ('1_chronicles', 2, 41): [296656, 296657, 296658, 296659, 296660, 296661, 296662, 296663], ('1_chronicles', 2, 42): [296664, 296665, 296666, 296667, 296668, 296669, 296670, 296671, 296672, 296673, 296674, 296675, 296676], ('1_chronicles', 2, 43): [296677, 296678, 296679, 296680, 296681, 296682], ('1_chronicles', 2, 44): [296683, 296684, 296685, 296686, 296687, 296688, 296689, 296690, 296691, 296692], ('1_chronicles', 2, 45): [296693, 296694, 296695, 296696, 296697, 296698, 296699], ('1_chronicles', 2, 46): [296700, 296701, 296702, 296703, 296704, 296705, 296706, 296707, 296708, 296709, 296710, 296711, 296712, 296713, 296714], ...}

In [22]:
import unicodedata
def raccs_common(text):
    d = {
        #ord('\N{COMBINING ACUTE ACCENT}'):None,
        ord('’'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('‘'): None,  # LEFT SINGLE QUOTATION MARK
        ord('“'): None,  # LEFT DOUBLE QUOTATION MARK
        ord('”'): None,  # RIGHT DOUBLE QUOTATION MARK
        ord('['): None,  # LEFT SINGLE QUOTATION MARK
        ord(']'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('-'): None,   # HYPHEN-MINUS
        ord('’'): None,   # HYPHEN-MINUS
        ord('⧼'): None,  # LEFT WHITE ANGLE BRACKET
        ord('⧽'): None,  # RIGHT WHITE ANGLE BRACKET
        ord('*'): None,   # ASTERISK
        ord('⇔'): None,  # LEFT RIGHT DOUBLE ARROW
        ord('〉'): None,  # GREATER-THAN SIGN
        ord('〈'): None,  # LESS-THAN SIGN
        ord('‿'): None,  # LOW LINE
        ord('«'): None,  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('»'): None,  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('‹'): None,  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        ord('›'): None,  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        ord('('): None,  # LEFT PARENTHESIS
        ord(')'): None,  # RIGHT PARENTHESIS
        ord('-') : None,  # HYPHEN-MINUS
        ord(';') : None,  # SEMICOLON
        ord(',') : None,  # comma
        ord('!') : None,  # !
        ord('?') : None,  # ?
        ord('.') : None,  # .
        }
    return unicodedata.normalize('NFD', text).translate(d)

def raccsGK(text):
    d = {
        ord('\N{COMBINING ACUTE ACCENT}'):None,
        0x0300: None,  # COMBINING GRAVE ACCENT
        0x0301: None,  # COMBINING ACUTE ACCENT
        0x0342: None,  # COMBINING GREEK PERISPOMENI
        0x0313: None,  # COMBINING COMMA ABOVE (PSILI)
        0x0314: None,  # COMBINING REVERSED COMMA ABOVE (DASIA)
        0x0308: None,  # COMBINING DIAERESIS
        0x0304: None,  # COMBINING MACRON
        0x0306: None,  # COMBINING BREVE
        0x0323: None,  # COMBINING DOT BELOW
        0x033E: None,  # COMBINING VERTICAL LINE ABOVE
        0x0345: None,  # COMBINING GREEK YPOGEGRAMMENI
        0x0360: None,  # COMBINING TILDE
        0x034F: None,  # COMBINING GRAPHEME JOINER
        0x035C: None,  # COMBINING DOUBLE BREVE
        0x035E: None,  # COMBINING DOUBLE MACRON
        0x037A: None,  # GREEK YPOGEGRAMMENI
        0x1FBD: None,  # GREEK KORONIS
        0x1FBF: None,  # GREEK PSILI
        0x1FBE: None,  # GREEK DASIA
        0x1FFF: None,   # GREEK OXIA
        ord('’'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('‘'): None,  # LEFT SINGLE QUOTATION MARK
        ord('“'): None,  # LEFT DOUBLE QUOTATION MARK
        ord('”'): None,  # RIGHT DOUBLE QUOTATION MARK
        ord('['): None,  # LEFT SINGLE QUOTATION MARK
        ord(']'): None,  # RIGHT SINGLE QUOTATION MARK
        ord('-'): None,   # HYPHEN-MINUS
        ord('’'): None,   # HYPHEN-MINUS
        ord('⧼'): None,  # LEFT WHITE ANGLE BRACKET
        ord('⧽'): None,  # RIGHT WHITE ANGLE BRACKET
        ord('*'): None,   # ASTERISK
        ord('⇔'): None,  # LEFT RIGHT DOUBLE ARROW
        ord('〉'): None,  # GREATER-THAN SIGN
        ord('〈'): None,  # LESS-THAN SIGN
        ord('‿'): None,  # LOW LINE
        ord('«'): None,  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('»'): None,  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
        ord('‹'): None,  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
        ord('›'): None,  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        ord('('): None,  # LEFT PARENTHESIS
        ord(')'): None,  # RIGHT PARENTHESIS
# nestrādā .... nooooooooooooooooooooooo
        ord('-') : None,  # HYPHEN-MINUS
        ord(';') : None,  # SEMICOLON
        ord(',') : None,  # comma
        ord('!') : None,  # !
        ord('?') : None,  # ?
        ord('.') : None,  # .
        }
    return unicodedata.normalize('NFD', raccs_common(text)).translate(d)
    
def raccsLV(text):
    d = {
        }
    return unicodedata.normalize('NFD', raccs_common(text)).translate(d)

In [23]:
raccsLV("āēšķžŗaeskzr,;- hohohoho āēĀŠŽŖĢ")

'āēšķžŗaeskzr hohohoho āēĀŠŽŖĢ'

In [24]:
from pathlib import Path
from tqdm import tqdm
save_path=Path("bible/")
DEBUG_RESULT_VERSES = 0
def split_str_tokened(input_string, tokens):
    result = []
    current_string = input_string
    
    for token in tokens:
        # Atrodam pirmo marķiera parādīšanās vietu
        token_index = current_string.find(token)
        #print(token_index)
        #print(f"::str:: {current_string} \n::token::  {token}")
        # Ja marķieris netiek atrasts, pārtraucam procesu
        if token_index == -1:
            break
            
        # Sadalām virkni: 
        # pirmā daļa līdz marķiera beigām (ieskaitot pašu marķieri)
        # otrā daļa - viss, kas paliek aiz marķiera
        split_pos = token_index + len(token)
        part = current_string[:split_pos]
        current_string = current_string[split_pos:].strip()

        result.append(part)
        

    if current_string:
        result.append(current_string)
    #print(result)
    #print("-"*50)
    #print(tokens)
    return result



# Lietošanas piemērs:
# k = [('book', 1, 1), 'vārds1', 'vārds2']
# split_str_tokened(teksts, [k[i] for i in range(1, len(k))])
#keyss = sorted(hb_g.groups.keys())
#for i, key in enumerate(keyss):
its = chapters_map.items()
lenits = len(its)
for i, (b, chapter), verses in enumerate(its):
    chapter_content = []
    #print(f"{b} {str(chapter)} ({i+1}/{lenits})")
    for key in tqdm(verses, desc=f"{b} {chapter}", leave=False):
    #[('genesis', 24, 65)]):
    #keyss):
    #[('daniel', 5, 31)]):
    #keyss):
    #[('psalms', 140, 1)]):
    #[('deuteronomy', 29, 2)]):
    #[('genesis', 15, 19)]):
    #[('genesis', 31, 55)]):
    #keyss):
        b, chapter, verse = key
        heb_text = " ".join(hb_g.get_group(key).sort_values("word")["form"].astype(str))
        chapter_dir = save_path / b / str(chapter)
        chapter_dir.mkdir(parents=True, exist_ok=True)
        
        l65_text=""
        if key in hb_to_l65.keys():
            kkey = hb_to_l65[key]
            if(kkey == None):
                l65_text="-"
            else:
                if not kkey[0][0]=="!":
                    l65_text=" ".join(l65_g.get_group(kkey).sort_values("word_idx")["text"].astype(str))
                else:
                    #merge
                    #l65_to_hb_merge[(('genesis', 15, 19), "kadmoniešus", "refajiešus")] = 
                    #(('genesis', 15, 19), ('genesis', 15, 20), ('genesis', 15, 21))
                    ##l65_to_hb_merge[(('deuteronomy', 29, 1), ('deuteronomy', 29, 2))]=('deuteronomy', 29, 2)
                    #print(kkey)
                    nkey = (kkey[0][1:], kkey[1], kkey[2])
                    #print("here")
                    #print(nkey)
                    for k, v in l65_to_hb_merge.items():
                        #merge will ALWAY have at least 2 items in key (either mergable verse Nr2 or splitstring Nr1)
                        if(isinstance(k[1], str) and k[0] == nkey):
                            
                            #case 1: lv verse has multiple hebrw verses in it
                            sstr = " ".join(l65_g.get_group(nkey).sort_values("word_idx")["text"].astype(str))
                            spArr = split_str_tokened(sstr, [k[i] for i in range(1, len(k))])
                            #print(spArr)
                            if(len(spArr) != len(v)):
                                raise Exception (f"could not tokenise properly!!!@ {k} to {v}")
                            for i, vsNm in enumerate(v):
                                if vsNm == key:
                                    l65_text=spArr[i]
                                    break
                            if not l65_text:
                                raise Exception (f"could not find verse part for the {key} at {k} to {v}")
                        elif(v==key):
                            #now this is inverse case of the above, l65 verses should be merged.
                            rslt = []
                            for mrg_verse in k:
                                rslt.append(" ".join(l65_g.get_group(mrg_verse).sort_values("word_idx")["text"].astype(str)))
                            l65_text = " ".join(rslt)
                            break
                    if not  l65_text:
                        raise Exception (f"key not found! {nkey} :: {key}")
        else:
            l65_text=" ".join(l65_g.get_group(key).sort_values("word_idx")["text"].astype(str))
        l65_text    
        if key in strongs_g.groups.keys():
            greek_text = " ".join(strongs_g.get_group(key).sort_values("word")["form"].astype(str))
        else:
            greek_text = "-"
        l65_text = raccsLV(l65_text)
        chapter_content.append(f"{heb_text}\n{greek_text}\n{l65_text}\n")
        if(DEBUG_RESULT_VERSES):
            print(key)
            print(heb_text)
            print(greek_text)
            print(l65_text)
            break
    #file_path.write_text
    file_path = save_path / b / f"{str(chapter)}.txt"
    #print("".join(chapter_content))#, encoding='utf-8')
    file_path.write_text("".join(chapter_content), encoding='utf-8')
    #break